version: "3.3"
services:

  jenkins:
    build:
      context: ./src/main/resources/jenkins
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home: